# Generated by Django 2.2 on 2019-10-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Before_and_afters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_photo', models.ImageField(upload_to='static/core/before_and_afters')),
                ('before_description', models.CharField(max_length=300)),
                ('after_photo', models.ImageField(upload_to='static/core/before_and_afters')),
                ('after_description', models.CharField(max_length=300)),
            ],
        ),
    ]
