# Generated by Django 2.2 on 2019-10-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='before_and_afters',
            name='after_photo',
            field=models.ImageField(upload_to='before_and_afters/'),
        ),
        migrations.AlterField(
            model_name='before_and_afters',
            name='before_photo',
            field=models.ImageField(upload_to='before_and_afters/'),
        ),
    ]
