# Generated by Django 2.2 on 2019-10-15 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191015_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='before_and_afters',
            name='job_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
