# Generated by Django 2.2 on 2019-10-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_before_and_afters_job_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='before_and_afters',
            name='job_date',
            field=models.DateField(),
        ),
    ]
