# Generated by Django 2.2 on 2019-10-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191015_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='before_and_afters',
            name='job_date',
            field=models.DateTimeField(),
        ),
    ]
