# Generated by Django 2.2 on 2019-10-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='before_and_afters',
            name='review_4_PROJECT',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Review'),
        ),
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Before_and_afters'),
        ),
    ]
