# Generated by Django 2.2 on 2019-10-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191017_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='before_and_afters',
            old_name='review_4_PROJECT',
            new_name='review_for_Project',
        ),
        migrations.AddField(
            model_name='before_and_afters',
            name='project_name',
            field=models.CharField(default='project', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='before_and_afters',
            name='review_for_Project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Review'),
        ),
    ]
