# Generated by Django 2.2 on 2019-10-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191017_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='before_and_afters',
            name='review_for_Project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Review'),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='job_category',
            field=models.CharField(choices=[('Roofing', 'Roofing'), ('Brickwork', 'Brickwork'), ('Driveway', 'Driveway'), ('Patio', 'Patio'), ('Turfing', 'Turfing'), ('Facias and Soffits', 'Facias & Soffits '), ('Guttering', 'Guttering'), ('Flat Roofing', 'Flat Roofing'), ('Plastering', 'Plastering'), ('Painting', 'Painting'), ('Rendering', 'Rendering'), ('Pebble Dashing', 'Pebble Dashing'), ('Fencing', 'Fencing'), ('Extensions', 'Extensions')], max_length=14),
        ),
    ]
