# Generated by Django 2.2 on 2019-10-18 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191017_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='before_and_afters',
            name='is_there_before_photos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='before_and_afters',
            name='review_for_Project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Review'),
        ),
    ]
