# Generated by Django 2.2 on 2019-10-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191018_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='before_and_afters',
            name='before_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='before_and_afters',
            name='before_photo',
            field=models.ImageField(blank=True, upload_to='before_and_afters/'),
        ),
        migrations.AlterField(
            model_name='before_and_afters',
            name='review_for_Project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Review'),
        ),
    ]
